= Meeting 15.10.24

== vorgeschlagene Richtung für die Umsetzung
* *konkrete Untersuchungspunkte:*
** Unsicherheit: Übertragung quantitativer Informationen mit "perfekter" Wahrscheinlichkeit zur qualitativen Risikomatrix -> Aufzeichnen der Folgen des Informationsverlustes 
** Einteilung: Risikomatrix-Aufbau und -Einteilung in Kategorien (z.B. "sehr wahrscheinlich", "sehr schwerwiegend")
** (Färbung)

* umzusetzendes Programm/ zu untersuchende Fragestellungen:
** *Ziel*: Überprüfung wie genau Matrix bei kleinen Streuungen von  Risiken (mit korrekt angenommenen Wahrscheinlichekiten) das Risiko in korrekte Prioritätsstufe (Farbe) einordnet
** Simulation mehrer tausend- zehntausende Versuche an gegebener Matrix der Norm DIN EN 50126
** normierte Maße der Achsen mit Häufigkeit und Ausmaß der Risiken von 0 bis 1
** ein bekannten Punkt, um den eine Verteilung gelegt wird (Koordiantenwerte dienen als Erwartungswerte) in qualitatives Risiko überführen
**d.h. 2 Zufallsvariablen mit spezieller noch zu findender bzw. variabler Varianz
** ansehen, in welcher Prioritätsstufe die simulierten zufällig mit gegebenen Verteilung gewählten Punkte landen -> *Worst-Case*: Gleichverteilt
**_Einflussparameter_: Varianz, Korrelation beider Koordinaten (Ausmaß und Häufigkeit) des Punktes an sich
** *Unsicherheit*: tatsächlicher Punkt mit beiden Werten ist unsicher, schwankt also um den Erwartungswert -> der feste Punkt hat seinen festen Platz in der Matrix, schwankende Punkte sind evt. in anderen Kategorien/Prioritäten, trotz geringer Streuung
** unabhängige Zufallssvariablen, dann Varianz und Punkte wählen (auch kann Wahrscheinlichekeit mit festem Schaden variiert werden)
** *Ergebnis*: Verteilung der Prioritäten (Farben/Klassen), in die die simulierten Punkte fallen in Form eines Histogramms
** Tool: Python, numpy, matplotlib


** nächster Schritt: interaktiv, GUI gestalten
** weiterer nächster Schritt: nachdem Risikomatrix linear aufgeteilt worden ist, mit Kategorienaufteilung experimentieren

== nächste Schritte bis nächstes Treffen:
* weitere Quellen durcharbeiten
* anhand DIN EN 50126 - Norm Literatur noch einmal rekapitulieren
* Prototyp zu beschriebenen Python-Programm erstellen und evt. Architektur/Konzept zu konkreter Umsetzung skizzieren